labels:
  - name: cog
    files:
      any:
        - "src/cogs/**"

  - name: handler
    files:
      any:
        - "src/handler/**"

  - name: documentation
    files:
      any:
        - "docs/**"
        - "**/*.md"

  - name: site
    files:
      any:
        - "site/**"

  - name: example
    files:
      any:
        - "example/**"

  - name: backend
    files:
      any:
        - "src/DevTools/backend/**"
        - "site/backend/**"

  - name: ui
    files:
      any:
        - "src/DevTools/ui/**"

  - name: static
    files:
      any:
        - "site/static/**"

  - name: priority-high
    files:
      any:
        - "**/*.py"

  - name: priority-medium
    files:
      any:
        - "**/*.html"
        - "**/*.css"
        - "**/*.js"
        - "**/*.yml"
        - "**/*.yaml"

  - name: priority-low
    files:
      any:
        - "**/*.json"
        - "**/*.txt"
        - "**/*.md"
        - "**/*.rst"

  - name: translation-message
    files:
      any:
        - "translation/message/**"

  - name: translation-commands
    files:
      any:
        - "translation/commands/**"

  - name: translation
    files:
      any:
        - "translation/**"

  - name: python
    files:
      any:
        - "**/*.py"

  - name: javascript
    files:
      any:
        - "**/*.js"

  - name: html
    files:
      any:
        - "**/*.html"

  - name: css
    files:
      any:
        - "**/*.css"
