cogs:
  files:
    any:
    - "src/cogs/**"

handler:
  files:
    any:
    - "src/handler/**"

documentation:
  files:
    any:
    - "docs/**"
    - "**/*.md"

site:
  files:
    any:
    - "site/**"

example:
  files:
    any:
    - "example/**"

backend:
  files:
    any:
    - "src/DevTools/backend/**"
    - "site/backend/**"

ui:
  files:
    any:
    - "src/DevTools/ui/**"

static:
  files:
    any:
    - "site/static/**"

priority-high:
  files:
    any:
    - "**/*.py"

priority-medium:
  files:
    any:
    - "**/*.html"
    - "**/*.css"
    - "**/*.js"
    - "**/*.yml"
    - "**/*.yaml"

priority-low:
  files:
    any:
    - "**/*.json"
    - "**/*.txt"
    - "**/*.md"
    - "**/*.rst"

translation-message:
  files:
    any:
    - "translation/message/**"

translation-commands:
  files:
    any:
    - "translation/commands/**"

translation:
  files:
    any:
    - "translation/**"

python:
  files:
    any:
    - "**/*.py"

javascript:
  files:
    any:
    - "**/*.js"

html:
  files:
    any:
    - "**/*.html"

css:
  files:
    any:
    - "**/*.css"