cogs:
- "src/cogs/**"

handler:
- "src/handler/**"

documentation:
- "docs/**"  
- "**/*.md"

site:
- "site/**"

example:
- "example/**"

backend:
- "src/DevTools/backend/**"
- "site/backend/**"

ui:
- "src/DevTools/ui/**"

static:
- "site/static/**"

priority-high:
- "**/*.py"

priority-medium:
- "**/*.html"
- "**/*.css"
- "**/*.js"
- "**/*.yml"
- "**/*.yaml"

priority-low:
- "**/*.json"
- "**/*.txt"
- "**/*.md"
- "**/*.rst"

translation-message:
- "translation/message/**"

translation-commands:
- "translation/commands/**"

translation:
- "translation/**"

python:
- "**/*.py"

javascript:
- "**/*.js"

html:
- "**/*.html"

css:
- "**/*.css"
