version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/req.txt  # <- hier die Datei für die Docs

sphinx:
  configuration: docs/conf.py  # Pfad zu deiner conf.py
